ln C:\proj\f\trunk\app\views\accounts\edit.html.erb  accounts\edit.html.erb 
ln C:\proj\f\trunk\app\views\comments\edit.html.erb comments_edit.html.erb
ln C:\proj\f\trunk\app\views\comments\index.html.erb comments_index.html.erb
ln C:\proj\f\trunk\app\views\comments\new.html.erb comments_new.html.erb
ln C:\proj\f\trunk\app\views\comments\show.html.erb comments_show.html.erb
ln C:\proj\f\trunk\app\views\comments\_new_comment.html.erb comments__new_comment.html.erb
ln C:\proj\f\trunk\app\views\comments\_show_comment.html.erb comments__show_comment.html.erb
ln C:\proj\f\trunk\app\views\favorites\create.erb favorites_create.erb
ln C:\proj\f\trunk\app\views_favoritesindex.html.erb index.html.erb favoritesindex.html.erb index.html.erb
ln C:\proj\f\trunk\app\views\favorites\_add_note.html.erb _add_note.html.erb favorites__add_note.html.erb _add_note.html.erb
ln C:\proj\f\trunk\app\views\favorites\_create.html.erb favorites__create.html.erb
ln C:\proj\f\trunk\app\views\favorites\_note_popup.html.erb favorites__note_popup.html.erb
ln C:\proj\f\trunk\app\views\favorites\_search_form.html.erb favorites__search_form.html.erb
ln C:\proj\f\trunk\app\views\favorites\_show_note.html.erb favorites__show_note.html.erb
ln C:\proj\f\trunk\app\views\friends\index.html.erb friends_index.html.erb
ln C:\proj\f\trunk\app\views\invite\index.html.erb invite_index.html.erb
ln C:\proj\f\trunk\app\views\invite\_contact.html.erb invite__contact.html.erb
ln C:\proj\f\trunk\app\views\layouts\comments.html.erb layouts_comments.html.erb
ln C:\proj\f\trunk\app\views\layouts\listings.html.erb layouts_listings.html.erb
ln C:\proj\f\trunk\app\views\layouts\listing_infos.html.erb layouts_listing_infos.html.erb
ln C:\proj\f\trunk\app\views\layouts\main.html.erb layouts_main.html.erb
ln C:\proj\f\trunk\app\views\layouts\registration.html.erb layouts_registration.html.erb
ln C:\proj\f\trunk\app\views\layouts\sessions.html.erb layouts_sessions.html.erb
ln C:\proj\f\trunk\app\views\layouts\users.html.erb layouts_users.html.erb
ln C:\proj\f\trunk\app\views\layouts\visuals.html.erb layouts_visuals.html.erb
ln C:\proj\f\trunk\app\views\listings\edit.html.erb listings_edit.html.erb
ln C:\proj\f\trunk\app\views\listings\index.html.erb listings_index.html.erb
ln C:\proj\f\trunk\app\views\listings\new.html.erb listings_new.html.erb
ln C:\proj\f\trunk\app\views\listings\show.html.erb listings_show.html.erb
ln C:\proj\f\trunk\app\views\listings\_form.html.erb listings__form.html.erb
ln C:\proj\f\trunk\app\views\listings\_search_form.html.erb listings__search_form.html.erb
ln C:\proj\f\trunk\app\views\listing_infos\edit.html.erb listing_infos_edit.html.erb
ln C:\proj\f\trunk\app\views\listing_infos\index.html.erb listing_infos_index.html.erb
ln C:\proj\f\trunk\app\views\listing_infos\new.html.erb listing_infos_new.html.erb
ln C:\proj\f\trunk\app\views\listing_infos\new.html.erb_dropdowns listing_infos\new.html.erb_dropdowns
ln C:\proj\f\trunk\app\views\listing_infos\show.html.erb listing_infos_show.html.erb
ln C:\proj\f\trunk\app\views\listing_infos\_create.html.erb listing_infos__create.html.erb
ln C:\proj\f\trunk\app\views\listing_infos\_form.html.erb listing_infos__form.html.erb
ln C:\proj\f\trunk\app\views\passwords\edit.html.erb passwords_edit.html.erb
ln C:\proj\f\trunk\app\views\passwords\new.html.erb passwords_new.html.erb
ln C:\proj\f\trunk\app\views\photos\edit.html.erb photos_edit.html.erb
ln C:\proj\f\trunk\app\views\photos\index.html.erb photos_index.html.erb
ln C:\proj\f\trunk\app\views\photos\new.html.erb photos_new.html.erb
ln C:\proj\f\trunk\app\views\photos\show.html.erb photos_show.html.erb
ln C:\proj\f\trunk\app\views\photos\_visuals_list.html.erb photos__visuals_list.html.erb
ln C:\proj\f\trunk\app\views\sessions\new.html.erb sessions_new.html.erb
ln C:\proj\f\trunk\app\views\shared\_comments_list_spacer.erb shared__comments_list_spacer.erb
ln C:\proj\f\trunk\app\views\shared\_comment_list.html.erb shared__comment_list.html.erb
ln C:\proj\f\trunk\app\views\shared\_comment_popup.html.erb shared__comment_popup.html.erb
ln C:\proj\f\trunk\app\views\shared\_create_comment.erb shared__create_comment.erb
ln C:\proj\f\trunk\app\views\shared\_flag.html.erb shared__flag.html.erb
ln C:\proj\f\trunk\app\views\shared\_flag_popup.html.erb shared__flag_popup.html.erb
ln C:\proj\f\trunk\app\views\shared\_inline_listing.html.erb shared__inline_listing.html.erb
ln C:\proj\f\trunk\app\views\shared\_listing.html.erb shared__listing.html.erb
ln C:\proj\f\trunk\app\views\shared\_listing_info.html.erb shared__listing_info.html.erb
ln C:\proj\f\trunk\app\views\shared\_listing_list.html.erb shared__listing_list.html.erb
ln C:\proj\f\trunk\app\views\shared\_listing_list_spacer.erb shared__listing_list_spacer.erb
ln C:\proj\f\trunk\app\views\shared\_locked_listing_info.html.erb shared__locked_listing_info.html.erb
ln C:\proj\f\trunk\app\views\shared\_login_form.html.erb shared__login_form.html.erb
ln C:\proj\f\trunk\app\views\shared\_main_navigation.html.erb shared__main_navigation.html.erb
ln C:\proj\f\trunk\app\views\shared\_my_listing_navigation.html.erb shared__my_listing_navigation.html.erb
ln C:\proj\f\trunk\app\views\shared\_new_comment.html.erb shared__new_comment.html.erb
ln C:\proj\f\trunk\app\views\shared\_notice.html.erb shared__notice.html.erb
ln C:\proj\f\trunk\app\views\shared\_show_comment.html.erb shared__show_comment.html.erb
ln C:\proj\f\trunk\app\views\shared\_show_listing.html.erb shared__show_listing.html.erb
ln C:\proj\f\trunk\app\views\shared\_submit_button.html.erb shared__submit_button.html.erb
ln C:\proj\f\trunk\app\views\tests\index.html.erb tests_index.html.erb
ln C:\proj\f\trunk\app\views\users\edit.html.erb users_edit.html.erb
ln C:\proj\f\trunk\app\views\users\index.html.erb users_index.html.erb
ln C:\proj\f\trunk\app\views\users\new.html.erb users_new.html.erb
ln C:\proj\f\trunk\app\views\users\show.html.erb users_show.html.erb
ln C:\proj\f\trunk\app\views\user_mailer\activation.html.erb user_mailer_activation.html.erb
ln C:\proj\f\trunk\app\views\user_mailer\forgot_password.html.erb user_mailer_forgot_password.html.erb
ln C:\proj\f\trunk\app\views\user_mailer\reset_password.html.erb user_mailer_reset_password.html.erb
ln C:\proj\f\trunk\app\views\user_mailer\signup_notification.html.erb user_mailer_signup_notification.html.erb
ln C:\proj\f\trunk\app\views\visuals\edit.html.erb visuals_edit.html.erb
ln C:\proj\f\trunk\app\views\visuals\index.html.erb visuals_index.html.erb
ln C:\proj\f\trunk\app\views\visuals\new.html.erb visuals_new.html.erb
ln C:\proj\f\trunk\app\views\visuals\show.html.erb visuals_show.html.erb
ln C:\proj\f\trunk\app\views\visuals\_visuals_list.html.erb visuals__visuals_list.html.erb
